name: TP5
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
 name: TP5
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: recuperer le code
        uses: actions/checkout@v4
      - name: installer python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: installer les dependencies
        run: pip install -r requirements.txt
      - name: installer flake8
        run: pip install flake8
      - name: executer lint
        run: flake8 app/ tests/
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: Depend de lint
        needs: lint
      - name: execute uniquement si lint reussi
        if: success()
      - name: install dependances
        run: pip install -r requirements.txt
      - name: executer pytest
        run: pytest tests/ -v --cov=src






